name: OITC
main: me.artish1.OITC.OITC
version: 3.4
author: artish1
api-version: 1.13
description: >
        One In The Chamber - Minigame
commands:
  oitc:
    description: The main command for OITC(One in the Chamber)
